import type { SemanticModel } from "../../contracts/semantic";

export const projectModel: SemanticModel = {
  id: "model-project",
  tenantId: "global",
  version: 1,
  defaultLocale: "fa-IR",
  name: { "fa-IR": "پروژه‌ها", "en-US": "Projects" },
  entities: [
    {
      id: "project",
      source: "projects",
      name: { "fa-IR": "پروژه", "en-US": "Project" },
      description: { "fa-IR": "پروژه‌های ساختمانی", "en-US": "Construction projects" },
      defaultDateField: "startDate",
      fields: [
        { id: "id", column: "id", type: "string", role: "dimension", hidden: true,
          label: { "fa-IR": "شناسه", "en-US": "ID" }, defaultAggregation: "countDistinct",
          allowedAggregations: ["count", "countDistinct"] },
        { id: "name", column: "name", type: "string", role: "dimension",
          label: { "fa-IR": "نام پروژه", "en-US": "Project Name" }, synonyms: ["عنوان پروژه", "title"] },
        { id: "province", column: "province", type: "string", role: "dimension",
          label: { "fa-IR": "استان", "en-US": "Province" }, synonyms: ["شهر", "استان‌ها", "region"] },
        { id: "status", column: "status", type: "string", role: "dimension",
          label: { "fa-IR": "وضعیت", "en-US": "Status" }, synonyms: ["مرحله", "state"] },
        { id: "buildingGroup", column: "buildingGroup", type: "string", role: "dimension",
          label: { "fa-IR": "گروه ساختمان", "en-US": "Building Group" } },
        { id: "area", column: "areaM2", type: "number", role: "measure",
          label: { "fa-IR": "مساحت (مترمربع)", "en-US": "Area (m²)" }, synonyms: ["متراژ", "زیربنا"],
          defaultAggregation: "sum", allowedAggregations: ["sum", "avg", "min", "max"],
          format: { kind: "number", decimals: 0, grouping: true } },
        { id: "score", column: "score", type: "number", role: "measure",
          label: { "fa-IR": "امتیاز ارزیابی", "en-US": "Assessment Score" }, synonyms: ["نمره", "امتیاز"],
          defaultAggregation: "avg", allowedAggregations: ["avg", "min", "max"],
          format: { kind: "number", decimals: 1 } },
        { id: "delayDays", column: "delayDays", type: "number", role: "measure",
          label: { "fa-IR": "تأخیر (روز)", "en-US": "Delay (days)" }, synonyms: ["تاخیر", "delay"],
          defaultAggregation: "avg", allowedAggregations: ["avg", "min", "max", "sum"],
          format: { kind: "number", decimals: 0 } },
        { id: "startDate", column: "startDate", type: "date", role: "date",
          label: { "fa-IR": "تاریخ شروع", "en-US": "Start Date" }, synonyms: ["زمان", "ماه", "سال"],
          format: { kind: "date", pattern: "yyyy/MM" } },
        { id: "dueDate", column: "dueDate", type: "date", role: "date",
          label: { "fa-IR": "موعد", "en-US": "Due Date" }, synonyms: ["سررسید", "deadline"],
          format: { kind: "date", pattern: "yyyy/MM" } },
      ],
    },
  ],
};
