#!/usr/bin/env bash
# Generate deploy/.env (fresh, server-only secrets) + deploy/certs/openiddict.pfx.
# Idempotent: whatever already exists is left untouched, so re-running NEVER rotates a
# live secret. External integrations (FarsNezam / SMS / Google / Nezam) are left blank
# for the operator to fill in afterwards.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT/deploy/.env"
CERT_DIR="$ROOT/deploy/certs"
CERT_PFX="$CERT_DIR/openiddict.pfx"

# Complex password (lower+digit from hex, plus upper+lower+digit+symbol suffix) — satisfies
# both SQL Server SA rules and ASP.NET Identity's default password policy.
gen_complex() { printf '%s#Aa9' "$(openssl rand -hex 14)"; }
# Opaque high-entropy token (hex = alphanumeric, no shell/url/connection-string-hostile chars).
gen_token()   { openssl rand -hex 32; }

if [ ! -f "$ENV_FILE" ]; then
  echo "[provision] generating fresh deploy/.env"
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/remote-provision.sh on first deploy to 185.206.94.116.
# Fresh, server-only secrets. Fill the EXTERNAL INTEGRATIONS block to enable those features.

# --- Public hosts (all behind the ArvanCloud CDN; origin = this box) ---
WEB_DOMAIN=mabhas19.myceo.ir
API_DOMAIN=api.mabhas19.myceo.ir
AUTH_DOMAIN=auth.myceo.ir
MINIO_DOMAIN=s3.mabhas19.myceo.ir
ANALYTICS_DOMAIN=analytic.myceo.ir
MUN_SANANDAJ_DOMAIN=mun-sanandaj.myceo.ir
STATUS_DOMAIN=status.myceo.ir
LANDING_PANEL_DOMAIN=landing-panel.myceo.ir
# Central user-management admin SPA (gated by the Administrator role at the IdP's api/admin).
ADMIN_DOMAIN=admin.myceo.ir
# The kurdnezam landing site is served on BOTH its own root domain and the portal subdomain.
# Both are CORS-allowed on the API (the site calls it from the browser for visit tracking + forms).
KURDNEZAM_DOMAIN=kurdnezam.myceo.ir
KURDNEZAM_ROOT_DOMAIN=kurdnezam.ir

# --- Infra secrets (generated) ---
MSSQL_SA_PASSWORD=$(gen_complex)
MINIO_ROOT_USER=mabhas19admin
MINIO_ROOT_PASSWORD=$(gen_token)
MINIO_BUCKET=mabhas19
OPENIDDICT_CERT_PASSWORD=$(gen_token)

# --- Auth / OIDC ---
# MABHAS19_WEB_CLIENT_SECRET is shared between the web (AUTH_MABHAS19_SECRET) and the IdP
# (Clients__Mabhas19Web__Secret); AUTH_SECRET encrypts the Auth.js session.
AUTH_SECRET=$(gen_token)
MABHAS19_WEB_CLIENT_SECRET=$(gen_token)
# plan-web is seeded unconditionally by the IdP (confidential client → needs a non-empty secret),
# even though plan.myceo.ir isn't hosted on this box.
PLAN_WEB_CLIENT_SECRET=$(gen_token)

# --- Seeded admin (IdP + API) — log in with these ---
ADMIN_EMAIL=amirkarami.dev@gmail.com
ADMIN_PASSWORD=$(gen_complex)

# --- EXTERNAL INTEGRATIONS (fill in to enable; safe to leave empty) ---
# FarsNezam (نظام مهندسی فارس) read-only SQL — engineer onboarding + project import:
FARSNEZAM_DB_CONN=
# Mobile OTP via msgway.com — the VPS public IP is whitelisted on msgway, so the auth container
# calls api.msgway.com directly. Set SMS_MSGWAY_APIKEY to enable real sending (empty => logs only).
SMS_PROVIDER=direct
SMS_MSGWAY_APIKEY=
SMS_MSGWAY_TEMPLATE_ID=13812
# Legacy relay fallback (unused when SMS_PROVIDER=direct):
SMS_RELAY_TOKEN=
# Google sign-in (OAuth web client id):
GOOGLE_CLIENT_ID=
# نظام مهندسی ساختمان project import:
NEZAM_BASE_URL=
NEZAM_API_KEY=
# mun-sanandaj municipality integration (KurdNezam read-only SQL + mahyapardaz REST bearer token).
# NON-EMPTY KURDNEZAM_DB_CONN enables the two 12h sync workers; leave both empty to disable.
KURDNEZAM_DB_CONN=
MUN_SANANDAJ_API_TOKEN=
# Analytics service (AI reporting on FarsNezam) — analytic.myceo.ir.
# Non-secret build/runtime toggles:
ANALYTICS_AI_FE_MODE=gateway
ANALYTICS_AI_MODEL=DeepSeek-R1-qwen-7b-awq
# Secrets (paste real values): ArvanCloud AI gateway (BaseUrl must end in /v1) + key, and the
# FarsNezam read-only SQL conn (NON-EMPTY enables the analytics SQL engine):
ANALYTICS_AI_BASE_URL=
ANALYTICS_AI_API_KEY=
ANALYTICS_DB_CONN=
EOF
  chmod 600 "$ENV_FILE"
  echo "[provision] deploy/.env created (chmod 600)"
else
  echo "[provision] deploy/.env already exists — leaving it untouched"
fi

# Ensure a KEY exists in .env (append if absent). Idempotent — never overwrites a live value.
ensure_env() {
  grep -qE "^$1=" "$ENV_FILE" 2>/dev/null || printf '%s=%s\n' "$1" "$2" >> "$ENV_FILE"
}

# status.myceo.ir — internal roadmap board. Backfill for .env files created before this service
# existed, and generate its Traefik basic-auth credential ONCE (hash stored in .env, password
# printed below). The apr1 hash's '$' chars are doubled to '$$' so docker-compose interpolation
# passes a single '$' through to the Traefik label.
ensure_env STATUS_DOMAIN status.myceo.ir

# kurdnezam CMS: the admin panel host + the two public site origins. Backfilled for .env files
# created before these services existed.
ensure_env LANDING_PANEL_DOMAIN landing-panel.myceo.ir
ensure_env KURDNEZAM_DOMAIN kurdnezam.myceo.ir
ensure_env KURDNEZAM_ROOT_DOMAIN kurdnezam.ir
# admin.myceo.ir — central user-management SPA. Backfilled for .env files created before it existed.
ensure_env ADMIN_DOMAIN admin.myceo.ir

# refahi.kurdnezam.ir — the engineers' welfare dashboard (سامانه رفاهی مهندسین). An unset domain
# would make the IdP seeder parse "https:///auth/callback" and abort, so it is always present.
ensure_env WALFARE_DOMAIN refahi.kurdnezam.ir

# msgway direct SMS — backfill the new keys for .env files created before direct sending existed.
# (SMS_MSGWAY_APIKEY stays empty here — the real key is a secret set out-of-band; ensure_env never
# overwrites a live value, so an already-configured key is preserved.)
ensure_env SMS_MSGWAY_APIKEY ""
ensure_env SMS_MSGWAY_TEMPLATE_ID 13812
if ! grep -qE '^STATUS_BASICAUTH=' "$ENV_FILE"; then
  STATUS_USER=admin
  STATUS_PW="$(openssl rand -hex 12)"
  STATUS_HASH="$(openssl passwd -apr1 "$STATUS_PW")"
  printf 'STATUS_BASICAUTH=%s:%s\n' "$STATUS_USER" "${STATUS_HASH//\$/\$\$}" >> "$ENV_FILE"
  echo "[provision] STATUS board basic-auth  user: $STATUS_USER  password: $STATUS_PW"
  echo "[provision]   (save it — only the apr1 hash is kept in .env; re-running won't rotate it)"
fi

# OpenIddict token-signing certificate (self-signed; fresh DB, so no token-continuity concern).
if [ ! -f "$CERT_PFX" ]; then
  echo "[provision] generating OpenIddict signing certificate"
  CERT_PW="$(grep -E '^OPENIDDICT_CERT_PASSWORD=' "$ENV_FILE" | cut -d= -f2-)"
  mkdir -p "$CERT_DIR"
  openssl req -x509 -newkey rsa:2048 -nodes -days 3650 \
    -subj "/CN=mabhas19-openiddict" \
    -keyout /tmp/m19-oi.key -out /tmp/m19-oi.crt >/dev/null 2>&1
  openssl pkcs12 -export -out "$CERT_PFX" \
    -inkey /tmp/m19-oi.key -in /tmp/m19-oi.crt \
    -passout pass:"$CERT_PW" >/dev/null 2>&1
  rm -f /tmp/m19-oi.key /tmp/m19-oi.crt
  # World-readable so the non-root app user inside the auth container can read it.
  # Safe: the PFX private key is encrypted with OPENIDDICT_CERT_PASSWORD (kept in the 600 .env).
  chmod 755 "$CERT_DIR"
  chmod 644 "$CERT_PFX"
  echo "[provision] deploy/certs/openiddict.pfx created"
else
  echo "[provision] openiddict.pfx already exists — leaving it untouched"
fi

# ASP.NET Data Protection key ring for the auth app (bind-mounted at /keys). It encrypts the
# login form's antiforgery token and the auth cookie, so it MUST survive container recreates —
# otherwise every redeploy breaks the next login POST ("key not found in the key ring") and
# signs everyone out. The auth image runs as UID 1654, so the folder must be owned by it.
KEYS_DIR="$ROOT/deploy/authkeys"
mkdir -p "$KEYS_DIR"
chown 1654:1654 "$KEYS_DIR" 2>/dev/null || sudo chown 1654:1654 "$KEYS_DIR"
chmod 700 "$KEYS_DIR"
echo "[provision] deploy/authkeys ready (owned by 1654)"

# Surface the seeded admin credentials once (the operator's own new secret) so they can log in.
echo "[provision] ADMIN_EMAIL=$(grep -E '^ADMIN_EMAIL=' "$ENV_FILE" | cut -d= -f2-)"
echo "[provision] ADMIN_PASSWORD=$(grep -E '^ADMIN_PASSWORD=' "$ENV_FILE" | cut -d= -f2-)"
echo "[provision] done"
