import type { SemanticModel } from "../../contracts/semantic";

// Frontend mirror of the backend KurdNezam semantic models
// (src/Infrastructure/Analytics/Sql/KurdNezamSemanticModelStore.cs). Used in REAL mode
// (VITE_USE_MOCK_API="false") for the Ask-AI dataset picker + auto-viz role hints.
// The backend remains authoritative for AI grounding + SQL; ids/sources/fields MUST match it.
// `column` = field id (the backend resolves the real column via ResolvedColumn = id).

export const ozInfoModel: SemanticModel = {
  id: "model-oz-info",
  tenantId: "global",
  version: 1,
  defaultLocale: "fa-IR",
  name: { "fa-IR": "اعضا و پروانه‌ها", "en-US": "Members & Licenses" },
  entities: [
    {
      id: "oz_info",
      source: "oz_info",
      name: { "fa-IR": "عضو", "en-US": "Member" },
      description: {
        "fa-IR": "اطلاعات عضویت و پروانه مهندسان استان کردستان",
        "en-US": "KurdNezam membership & license info",
      },
      fields: [
        { id: "Ozviat", column: "Ozviat", type: "number", role: "dimension",
          label: { "fa-IR": "کد عضویت", "en-US": "Membership No" }, synonyms: ["عضویت", "کد عضو"] },
        { id: "PayeT", column: "PayeT", type: "number", role: "dimension",
          label: { "fa-IR": "پایه طراحی", "en-US": "Design Grade" },
          synonyms: ["پایه طراحی", "طراح", "design grade"] },
        { id: "PayeNez", column: "PayeNez", type: "number", role: "dimension",
          label: { "fa-IR": "پایه نظارت", "en-US": "Supervision Grade" },
          synonyms: ["پایه نظارت", "ناظر", "supervision"] },
        { id: "MaxPaye", column: "MaxPaye", type: "number", role: "dimension",
          label: { "fa-IR": "بالاترین پایه", "en-US": "Max Grade" }, synonyms: ["بالاترین پایه"] },
        { id: "IsHogh", column: "IsHogh", type: "number", role: "dimension",
          label: { "fa-IR": "حقیقی/حقوقی", "en-US": "Legal/Natural" },
          synonyms: ["حقوقی", "حقیقی"] },
        { id: "TypDftr", column: "TypDftr", type: "number", role: "dimension",
          label: { "fa-IR": "نوع شخصیت", "en-US": "Entity Type" },
          synonyms: ["دفتر", "مجری", "آزمایشگاه"] },
        { id: "ExpDate", column: "ExpDate", type: "string", role: "dimension",
          label: { "fa-IR": "اعتبار پروانه", "en-US": "License Expiry" },
          synonyms: ["اعتبار", "انقضا", "پروانه"] },
        { id: "RegInErja", column: "RegInErja", type: "number", role: "dimension",
          label: { "fa-IR": "ثبت‌نام در ارجاع", "en-US": "Referral Registered" },
          synonyms: ["ارجاع", "ثبت نام ارجاع"] },
        { id: "Reshte", column: "Reshte", type: "string", role: "dimension",
          label: { "fa-IR": "رشته", "en-US": "Field" },
          synonyms: ["رشته", "معماری", "عمران", "برق", "مکانیک"] },
        { id: "LastWorkDate", column: "LastWorkDate", type: "string", role: "dimension",
          label: { "fa-IR": "آخرین تخصیص", "en-US": "Last Assignment" },
          synonyms: ["آخرین کار", "تخصیص"] },
        { id: "ActiveInErja", column: "ActiveInErja", type: "number", role: "measure",
          label: { "fa-IR": "تعداد شرکت در ارجاع", "en-US": "Referral Participations" },
          synonyms: ["شرکت در ارجاع"],
          defaultAggregation: "sum", allowedAggregations: ["sum", "avg", "min", "max"],
          format: { kind: "number", decimals: 0, grouping: true } },
      ],
    },
  ],
};

export const engineerProjectsModel: SemanticModel = {
  id: "model-engineer-projects",
  tenantId: "global",
  version: 1,
  defaultLocale: "fa-IR",
  name: { "fa-IR": "کارکرد پروژه‌ای مهندسان", "en-US": "Engineer Project Work" },
  entities: [
    {
      id: "engineer_projects",
      source: "engineer_projects",
      name: { "fa-IR": "تخصیص", "en-US": "Assignment" },
      description: {
        "fa-IR": "تخصیص مهندسان به پروژه‌ها و متراژ کارکرد",
        "en-US": "Engineer-to-project assignments with worked area",
      },
      fields: [
        { id: "ProjectNo", column: "ProjectNo", type: "string", role: "dimension",
          label: { "fa-IR": "شماره پرونده", "en-US": "File No" }, synonyms: ["پرونده", "پروژه"] },
        { id: "Ozviat", column: "Ozviat", type: "number", role: "dimension",
          label: { "fa-IR": "کد عضویت", "en-US": "Membership No" }, synonyms: ["عضویت", "مهندس"] },
        { id: "TypEng", column: "TypEng", type: "number", role: "dimension",
          label: { "fa-IR": "نوع خدمت", "en-US": "Service Type" }, synonyms: ["خدمت", "نقش"] },
        { id: "IsHogh", column: "IsHogh", type: "number", role: "dimension",
          label: { "fa-IR": "حقیقی/حقوقی", "en-US": "Legal/Natural" }, synonyms: ["حقوقی", "حقیقی"] },
        { id: "IsErja", column: "IsErja", type: "number", role: "dimension",
          label: { "fa-IR": "از طریق ارجاع", "en-US": "Via Referral" }, synonyms: ["ارجاع"] },
        { id: "IsHal", column: "IsHal", type: "number", role: "dimension",
          label: { "fa-IR": "وضعیت جاری", "en-US": "In Progress" }, synonyms: ["در حال کار", "جاری"] },
        { id: "RegDate", column: "RegDate", type: "string", role: "dimension",
          label: { "fa-IR": "تاریخ ثبت", "en-US": "Registered" }, synonyms: ["تاریخ", "date"] },
        { id: "TypProject", column: "TypProject", type: "number", role: "dimension",
          label: { "fa-IR": "نوع پروژه", "en-US": "Project Type" }, synonyms: ["نوع"] },
        { id: "CityId", column: "CityId", type: "number", role: "dimension",
          label: { "fa-IR": "شهر", "en-US": "City" }, synonyms: ["شهرستان", "city"] },
        { id: "HasPayan", column: "HasPayan", type: "number", role: "dimension",
          label: { "fa-IR": "پایان‌کار", "en-US": "Completion Cert" }, synonyms: ["پایان کار"] },
        { id: "ExitTyp", column: "ExitTyp", type: "number", role: "dimension",
          label: { "fa-IR": "نوع خروج", "en-US": "Exit Type" }, synonyms: ["خروج"] },
        { id: "IsAfza", column: "IsAfza", type: "number", role: "dimension",
          label: { "fa-IR": "افزایش بنا", "en-US": "Extension" }, synonyms: ["افزایش بنا", "توسعه"] },
        { id: "Meter", column: "Meter", type: "number", role: "measure",
          label: { "fa-IR": "متراژ", "en-US": "Area" }, synonyms: ["متراژ", "مترمربع", "area"],
          defaultAggregation: "sum", allowedAggregations: ["sum", "avg", "min", "max"],
          format: { kind: "number", decimals: 0, grouping: true } },
        { id: "MeterFull", column: "MeterFull", type: "number", role: "measure",
          label: { "fa-IR": "متراژ کل", "en-US": "Total Area" }, synonyms: ["متراژ کل"],
          defaultAggregation: "sum", allowedAggregations: ["sum", "avg", "min", "max"],
          format: { kind: "number", decimals: 0, grouping: true } },
      ],
    },
  ],
};
